<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/09/25 01:35:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
