<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/03 00:57:40

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => '5string',
  'name' => 'doctrine',
)),);
