<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/13 23:12:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => '5string',
  'name' => 'doctrine',
)),);
